name: MongoDB

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 14 * * 2" # 2pm Patch Tuesday

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  mongodb-build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: mongodb

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v2

      - name: "Setup: Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: matthewbaggett
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: "Setup: Login to GHCR"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: matthewbaggett
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        name: Build & Push
        with:
          context: mongodb
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: |
            gone/mongodb
            benzine/mongodb
            ghcr.io/benzine-framework/mongodb
